name: M2P-ETL-ALL

# trigger the workflow when someone pushes the code to repo
on:
  push:
    branches:
      - '*'         # matches every branch

jobs:
  build:
    # run the below steps on a fresh instance of a virtual environment
    runs-on: ubuntu-latest

    steps:
      # fetch and checkout the current commit
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show GitHub Reference
        run: |
          echo ${GITHUB_REF:10}

      # code smell the project
      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          sudo apt-get install python3-setuptools

      - name: Run Pylint
        run: |
          cp ./tests/.pylintrc .
          cp ./tests/lint.py ./src/
          pip3 install --no-cache-dir -r ./tests/requirements.txt
          pip3 install --no-cache-dir -r requirements.txt
          python3 ./src/lint.py --path ./src --threshold 9.5
